apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-demo
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/mi-cluster/apps/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m